version: '3'

services:
    web:
        build: .
        command: python3 manage.py runserver --settings=knode.settings 0.0.0.0:8000
        container_name: knodev
        volumes:
            - .:/knodev
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - ./.env
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
volumes:
  postgres_data:
